#!/bin/bash
apt update -y
apt install apache2 unzip -y
systemctl start apache2
cd /tmp
wget htttps://www.tooplate.com/zip-templates/2130_waso_strategy.zip
unzip 2130_waso_strategy.zip
cp -R/2130_waso_strategy/*/var/www/html
